# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171205_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='pub_time',
            new_name='time',
        ),
    ]
